env:
  browser: true
  es2020: true
  node: true
  "jest/globals": true
extends:
  - "plugin:react/recommended"
  - "plugin:sonarjs/recommended"
  - "eslint:recommended"
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - sonarjs
  - jest
rules:
  {
    "jest/no-disabled-tests": "warn",
    "jest/no-focused-tests": "error",
    "jest/no-identical-title": "error",
    "jest/prefer-to-have-length": "warn",
    "jest/valid-expect": "error",
    "react/display-name": "off",
  }
