version: "3.8"
services:
  ui:
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - ../:/app/
