version: "3.8"
services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    command: sh /app/_dev/scripts/build.sh
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - MAIN_PROJ=FantasyBaseball.PositionService
      - POSITION_DATABASE=position_database
      - POSITION_DATABASE_HOST=database
      - POSITION_DATABASE_PASSWORD=postgres
      - POSITION_DATABASE_USER=postgres
      - SONAR_CODE_EXCLUSIONS=Migrations/*.cs
      - SONAR_COVERGE_EXCLUSIONS=Migrations/*.cs
      - SONAR_KEY=fantasy-baseball-position
      - SONAR_URL=http://sonarqube.schultz.local/
      - VERSION=${VERSION_NUMBER}
    ports:
      - "8080:8080"
    volumes:
      - ../:/app/
  database:
    build: database/
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=position_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 30s
      retries: 5
    volumes:
      - data_volume:/var/lib/postgresql/data
volumes:
  data_volume:
