kind: Deployment
apiVersion: apps/v1
metadata:
  name: ui
  namespace: baseball
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: nschultz/fantasy-baseball-ui:{{version}}
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: PLAYER_API_URL
              value: "http://baseball-player-api.schultz.local"
            - name: POSITION_API_URL
              value: "http://baseball-position-api.schultz.local"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
